services:
    node:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            # - 127.0.0.1:9229:9229
            - 127.0.0.1:3000:3000
        env_file:
            - .env
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        command: npm run ${NODE_ENV:-development}
        # command: tail -f /dev/null #idle container
volumes:
    node_modules:
