services:
    node:
        build: .
        restart: unless-stopped
        volumes:
            - ./:/app
            - node_modules:/app/node_modules
        working_dir: /app
        env_file:
            - .env
        ports:
            - 127.0.0.1:80:3000
        command: npm run ${NODE_ENV:-development}
    chrome:
        image: 'browserless/chrome:latest'
        restart: unless-stopped
volumes:
    node_modules:
